DROP TABLE NZR_DP_SUBSCRIPTION CASCADE CONSTRAINTS;
DROP TABLE NZR_DP_BATCH CASCADE CONSTRAINTS;
DROP TABLE NZR_DP_BATCH_DETAIL CASCADE CONSTRAINTS;


CREATE TABLE NZR_DP_SUBSCRIPTION
(
	SUBSCRIPTION_SKEY    INTEGER NOT NULL ,
	DC_SKEY              INTEGER NOT NULL ,
	HOST_SKEY            INTEGER NULL ,
	TARGET_DATABASE_NAME    VARCHAR2(30),
	MINIMAL_DELAY        INTEGER NOT NULL ,
	SUBSCRIPTION_STATUS  NUMBER NOT NULL ,
	DROP_IF_EXISTS       INTEGER NOT NULL
	    CONSTRAINT NZR_DP_SUBSCR_DROP CHECK(DROP_IF_EXISTS IN (1, 0))
);

CREATE UNIQUE INDEX XPKNZR_DP_SUBSCRIPTION ON NZR_DP_SUBSCRIPTION
(SUBSCRIPTION_SKEY   ASC);

ALTER TABLE NZR_DP_SUBSCRIPTION
	ADD CONSTRAINT  XPKNZR_DP_SUBSCRIPTION PRIMARY KEY (SUBSCRIPTION_SKEY);

CREATE TABLE NZR_DP_BATCH
(
        DP_BATCH_SKEY          INTEGER NOT NULL,
	SUBSCRIPTION_SKEY    INTEGER NOT NULL ,
	DC_SKEY                    INTEGER NOT NULL,
	DC_BATCH_SKEY          INTEGER NOT NULL ,
	DP_BATCH_START_TS   TIMESTAMP NOT NULL ,
	DP_BATCH_END_TS       TIMESTAMP NULL ,
	DP_BATCH_STATUS      VARCHAR2(10) NOT NULL ,
	   CONSTRAINT NZR_CNK_DP_BATCH_STATUS CHECK (DP_BATCH_STATUS IN ('RUNNING', 'COMPLETED', 'ERROR')),
	DP_BATCH_TYPE          VARCHAR2(10) NOT NULL 
	   CONSTRAINT NZR_CHK_DP_BATCH_TYPE CHECK (DP_BATCH_TYPE IN ('I', 'F'))
);

--CREATE UNIQUE INDEX NZR_UNIQ_DP_BATCH ON NZR_DP_BATCH
--(SUBSCRIPTION_SKEY   ASC, DC_BATCH_SKEY  ASC);

ALTER TABLE NZR_DP_BATCH
	ADD CONSTRAINT  NZR_PK_DP_BATCH PRIMARY KEY (DP_BATCH_SKEY);

ALTER TABLE NZR_DP_BATCH
   ADD CONSTRAINT NZR_DP_BATCH_FK1 FOREIGN KEY (DC_BATCH_SKEY)
      REFERENCES NZR_DC_BATCH (DC_BATCH_SKEY) ON DELETE CASCADE;
      
ALTER TABLE NZR_DP_BATCH
  ADD CONSTRAINT NZR_DP_BATCH_FK2 FOREIGN KEY (SUBSCRIPTION_SKEY)
      REFERENCES NZR_DP_SUBSCRIPTION (SUBSCRIPTION_SKEY) ON DELETE CASCADE;
      
ALTER TABLE NZR_DP_BATCH
   ADD CONSTRAINT NZR_DP_BATCH_FK3 FOREIGN KEY (DC_SKEY)
      REFERENCES NZR_DC_SET (DC_SKEY) ON DELETE CASCADE;
      
CREATE TABLE NZR_DP_BATCH_DETAIL
(
        DP_BATCH_DTL_SKEY 		INTEGER NOT NULL,
	DP_BATCH_SKEY                  INTEGER NOT NULL,
	SUBSCRIPTION_SKEY      		INTEGER NOT NULL ,
--	DC_SKEY                      	INTEGER NULL ,
	DC_BATCH_SKEY            	INTEGER NOT NULL ,
	DC_BATCH_DTL_SKEY     		INTEGER NOT NULL ,
	DST_OBJECT_ID             	INTEGER NOT NULL ,
	DP_BATCH_START_TS           	DATE NOT NULL ,
	DP_BATCH_END_TS              	DATE NULL ,
	TABLE_SKEY                  	INTEGER NOT NULL ,
	INSERT_CNT                  	INTEGER NULL ,
	DP_BATCH_DTL_STATUS        	VARCHAR2(10) NOT NULL 
	     CONSTRAINT NZR_CHK_DP_BATCH_DTL_STATUS CHECK (DP_BATCH_DTL_STATUS IN ('RUNNING', 'COMPLETED', 'ERROR')),
	DELETE_CNT                       INTEGER NULL ,
	DDL_FLAG                         INTEGER NULL ,
	ACTION_CODE                      INTEGER NOT NULL  
             CONSTRAINT NZR_CNK_ACTION_CODE CHECK (ACTION_CODE BETWEEN 0 and 9)	--See Script-Naming-Rules.xls for codes
);

--CREATE UNIQUE INDEX XPKNZR_DP_BATCH_DETAIL ON NZR_DP_BATCH_DETAIL
--(SUBSCRIPTION_SKEY   ASC, DC_BATCH_SKEY   ASC, DC_BATCH_DTL_SKEY   ASC);

ALTER TABLE NZR_DP_BATCH_DETAIL
	ADD CONSTRAINT NZR_PK_DP_BATCH_DTL_SKEY PRIMARY KEY (DP_BATCH_DTL_SKEY);
	
ALTER TABLE NZR_DP_BATCH_DETAIL
   ADD CONSTRAINT NZR_DP_BATCH_DTL_FK1 FOREIGN KEY (SUBSCRIPTION_SKEY)
       REFERENCES NZR_DP_SUBSCRIPTION(SUBSCRIPTION_SKEY) ON DELETE CASCADE;
       
--ALTER TABLE NZR_DP_BATCH_DETAIL
   --ADD CONSTRAINT NZR_DP_BATCH_DTL_FK2 FOREIGN KEY (DC_SKEY)
     --  REFERENCES NZR_DC_SET(DC_SKEY);
       
ALTER TABLE NZR_DP_BATCH_DETAIL
   ADD CONSTRAINT NZR_DP_BATCH_DTL_FK3 FOREIGN KEY (DC_BATCH_SKEY)
       REFERENCES NZR_DC_BATCH(DC_BATCH_SKEY) ON DELETE CASCADE;
       
ALTER TABLE NZR_DP_BATCH_DETAIL
   ADD CONSTRAINT NZR_DP_BATCH_DTL_FK4 FOREIGN KEY (DC_BATCH_DTL_SKEY)
       REFERENCES NZR_DC_BATCH_DETAIL(DC_BATCH_DTL_SKEY) ON DELETE CASCADE;
       
ALTER TABLE NZR_DP_BATCH_DETAIL
   ADD CONSTRAINT NZR_DP_BATCH_DTL_FK5 FOREIGN KEY (TABLE_SKEY)
       REFERENCES NZR_DC_DETAIL(TABLE_SKEY) ON DELETE CASCADE;
       
ALTER TABLE NZR_DP_BATCH_DETAIL
   ADD CONSTRAINT NZR_DP_BATCH_DTL_FK6 FOREIGN KEY (DP_BATCH_SKEY)
       REFERENCES NZR_DP_BATCH(DP_BATCH_SKEY) ON DELETE CASCADE;

